### PR TITLE
Fix machinepool cluster name issue

### LINKED ISSUE #324: OCIManagedCluster with different name than Cluster object does not create machine pools
**What happened**:
OCIManagedCluster with different name than Cluster object does not create machine pools

**What you expected to happen**:
Machinepools should be created

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- CAPOCI version:
- Cluster-API version (use `clusterctl version`):
- Kubernetes version (use `kubectl version`):
- Docker version (use `docker info`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shyamradhakrishnan**
**What this PR does / why we need it**:
Fix machinepool infra cluster lookup issue

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #324

### CODE REVIEW

**Comment by shyamradhakrishnan** [comment]
unit test
```
?   	github.com/oracle/cluster-api-provider-oci	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/api/v1beta1	51.371s	coverage: 23.7% of statements
ok  	github.com/oracle/cluster-api-provider-oci/api/v1beta2	0.045s	coverage: 15.6% of statements
?   	github.com/oracle/cluster-api-provider-oci/cloud/config	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/metrics	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/cloud/ociutil	0.004s	coverage: 19.6% of statements
ok  	github.com/oracle/cluster-api-provider-oci/cloud/scope	241.403s	coverage: 75.2% of statements
?   	github.com/oracle/cluster-api-provider-oci/cloud/scope/mocks	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/base	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/base/mock_base	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute/mock_compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/computemanagement	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/computemanagement/mock_computemanagement	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/containerengine	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/containerengine/mock_containerengine	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity/mock_identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/loadbalancer	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/loadbalancer/mock_lb	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer/mock_nlb	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn/mock_vcn	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/cloud/util	0.143s	coverage: 73.4% of statements
ok  	github.com/oracle/cluster-api-provider-oci/controllers	27.178s	coverage: 60.3% of statements
ok  	github.com/oracle/cluster-api-provider-oci/exp/api/v1beta1	13.845s	coverage: 15.2% of statements
ok  	github.com/oracle/cluster-api-provider-oci/exp/api/v1beta2	0.016s	coverage: 4.8% of statements
ok  	github.com/oracle/cluster-api-provider-oci/exp/controllers	0.457s	coverage: 56.4% of statements
?   	github.com/oracle/cluster-api-provider-oci/feature	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/version	[no test files]
go tool cover -func=coverage.out -o coverage.txt
go tool cover -html=coverage.out -o coverage.html
```

File: controllers/ocimachine_controller.go [hunk 1]
```diff
@@ -189,6 +195,10 @@ func (r *OCIMachineReconciler) SetupWithManager(ctx context.Context, mgr ctrl.Ma
 			&infrastructurev1beta2.OCICluster{},
 			handler.EnqueueRequestsFromMapFunc(r.OCIClusterToOCIMachines()),
 		).
+		Watches(
```
Comment (shyamradhakrishnan) [inline controllers/ocimachine_controller.go:198]: While testing the self managed nodes today, I noticed that there is a timing issue. The OKE cluster creation is taking slightly longer than expected, and since we are not watching OCIManagedCluster, the machine reconciliation is not happening quickly as it is in exponential backoff loop(data secret lookup error as the control plane is not initialized).I had noticed this behaviour earlier, but this is more noticeable today.

File: exp/controllers/ocimanaged_machinepool_controller.go [hunk 2]
```diff
@@ -117,7 +117,7 @@ func (r *OCIManagedMachinePoolReconciler) Reconcile(ctx context.Context, req ctr
 	ociManagedCluster := &infrastructurev1beta2.OCIManagedCluster{}
 	ociClusterName := client.ObjectKey{
 		Namespace: cluster.Namespace,
-		Name:      cluster.Name,
+		Name:      cluster.Spec.InfrastructureRef.Name,
```
Comment (shyamradhakrishnan) [inline exp/controllers/ocimanaged_machinepool_controller.go:120]: this is the actual issue we fixed, the problem is that we were assuming cluster name == infra cluster name which is not true. Infra cluster name should be looked up via spec, we were already doing it in machine controller.

File: exp/controllers/ocimanaged_machinepool_controller.go [hunk 3]
```diff
@@ -216,7 +216,7 @@ func managedClusterToManagedMachinePoolMapFunc(c client.Client, gvk schema.Group
 	return func(ctx context.Context, o client.Object) []reconcile.Request {
 		ociCluster, ok := o.(*infrastructurev1beta2.OCIManagedCluster)
 		if !ok {
-			panic(fmt.Sprintf("Expected a OCIManagedControlPlane but got a %T", o))
```
Comment (shyamradhakrishnan) [inline exp/controllers/ocimanaged_machinepool_controller.go:219]: minor error in logs

File: test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-virtual/cluster.yaml [hunk 4]
```diff
@@ -9,7 +9,7 @@ spec:
   infrastructureRef:
     apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
     kind: OCIManagedCluster
-    name: "${CLUSTER_NAME}"
+    name: "${CLUSTER_NAME}-virtual"
```
Comment (shyamradhakrishnan) [inline test/e2e/data/infrastructure-oci/v1beta2/cluster-template-managed-virtual/cluster.yaml:12]: change to make sure that the actual bug fix works

**Review by joekr — APPROVED** [review]
