### PR TITLE
Fix bug where clusterctl move does not work, and add correct default …

### LINKED ISSUE #73: clusterctl move does not work with CAPOCI
**What happened**:
clusterctl move does not work with CAPOCI. The reconciliation is failing with the below error 
```
cluster api tags have been modified out of context
```

**What you expected to happen**:

Reconciliation should still happen

**How to reproduce it (as minimally and precisely as possible)**:

Use clusterctl move of an OCICluster
**Anything else we need to know?**:

CAPOCI is using the cluster UID as the resource identifier and tags all created resources with this tag. But during the move operation, the clusters gets a new UID which throws the modified out of context error.

**Environment:**

- CAPOCI version: 
- Cluster-API version (use `clusterctl version`):
- Kubernetes version (use `kubectl version`):
- Docker version (use `docker info`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shyamradhakrishnan**
Fix bug where clusterctl move does not work, and add correct default label

**What this PR does / why we need it**:

clusterctl move was not working in CAPOCI. This was because CAPOCI used the cluster UID to tag all OCI resources created, and during reconciliation, made sure that the tags matched. But during move, the cluster UID changes. So we cannot use cluster UID as the tag. Instead what we will do is to generate UID in the defaulter and use that to tag the OCI resources. This UID will not changes as it is not the auto-generated tag.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #73

### CODE REVIEW

**Comment by shyamradhakrishnan** [comment]
Unit test output
```
Using cached envtest tools from /Users/shyaradh/oke/src/github.com/oracle/cluster-api-provider-oci/testbin
setting up env vars
?   	github.com/oracle/cluster-api-provider-oci	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/api/v1beta1	2.839s	coverage: 7.8% of statements
?   	github.com/oracle/cluster-api-provider-oci/cloud/config	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/cloud/ociutil	0.521s	coverage: 30.3% of statements
ok  	github.com/oracle/cluster-api-provider-oci/cloud/scope	180.930s	coverage: 81.9% of statements
?   	github.com/oracle/cluster-api-provider-oci/cloud/scope/mocks	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute/mock_compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity/mock_identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer/mock_nlb	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn/mock_vcn	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/controllers	32.241s	coverage: 71.0% of statements
```
e2e test output
```
• [SLOW TEST:563.289 seconds]
Workload cluster creation
/home/ubuntu/go/src/github.com/oracle/cluster-api-provider-oci/test/e2e/cluster_test.go:49
  ClusterClass - with 1 control-plane nodes and 1 worker nodes [PRBlocking]
  /home/ubuntu/go/src/github.com/oracle/cluster-api-provider-oci/test/e2e/cluster_test.go:470
------------------------------
STEP: Tearing down the management cluster


Ran 5 of 21 Specs in 1703.699 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 16 Skipped
```

File: api/v1beta1/ocicluster_webhook.go [hunk 1]
```diff
@@ -24,19 +24,27 @@ import (
...
 )
 
 // +kubebuilder:webhook:verbs=create;update,path=/validate-infrastructure-cluster-x-k8s-io-v1beta1-ocicluster,mutating=false,failurePolicy=fail,matchPolicy=Equivalent,groups=infrastructure.cluster.x-k8s.io,resources=ociclusters,versions=v1beta1,name=validation.ocicluster.infrastructure.cluster.x-k8s.io,sideEffects=None,admissionReviewVersions=v1beta1
+// +kubebuilder:webhook:verbs=create;update,path=/mutate-infrastructure-cluster-x-k8s-io-v1beta1-ocicluster,mutating=true,failurePolicy=fail,matchPolicy=Equivalent,groups=infrastructure.cluster.x-k8s.io,resources=ociclusters,versions=v1beta1,name=default.ocicluster.infrastructure.cluster.x-k8s.io,sideEffects=None,admissionReviewVersions=v1;v1beta1
+
+func (c *OCICluster) Default() {
+	if c.Spec.OCIResourceIdentifier == "" {
+		c.Spec.OCIResourceIdentifier = string(uuid.NewUUID())
+	}
+}
```
Comment (joekr) [inline api/v1beta1/ocicluster_webhook.go:47]: Do we need a test to make sure this is set?

Comment (joekr) [reply api/v1beta1/ocicluster_webhook.go:47]: Also should we some how validate this exists during create? I believe the mutation happens followed by verification.

File: config/default/manager_image_patch.yaml [hunk 2]
```diff
@@ -8,5 +8,5 @@ spec:
     spec:
       containers:
         # Change the value of image field below to your controller image URL
-        - image:  ghcr.io/oracle/cluster-api-oci-controller-amd64:dev
+        - image: iad.ocir.io/odx-mockcustomer/cluster-api-oci-controller-amd64:dev
```
Comment (joekr) [inline config/default/manager_image_patch.yaml:11]: this shouldn't be changed.

File: config/default/kustomization.yaml [hunk 3]
```diff
@@ -10,7 +10,7 @@ namePrefix: capoci-
 
 # Labels to add to all resources and selectors.
 commonLabels:
-  cluster.x-k8s.io/v1beta1: v1beta1
+  cluster.x-k8s.io/provider: "infrastructure-oci"
```
Comment (joekr) [inline config/default/kustomization.yaml:13]: don't we still want to add the version label?

**Review by joekr — CHANGES_REQUESTED** [review]

File: config/default/kustomization.yaml (hunk 3 above)
Comment (shyamradhakrishnan) [reply config/default/kustomization.yaml:13]: as discussed, the version labels is added in the crd/kustomization.yaml folder

**Review by joekr — APPROVED** [review]
