### PR TITLE
Retry on delete backend failure

### LINKED ISSUE #331: Reconciliation not properly done: capioci proceeds with machine creation when loadbalancer is in Creating state
**What happened**:
Triggered a cluster creation in our private environment and it failed with the following CRD failure: APIServerLoadBalancerReconciliationFailed and BackendAdditionFailed errors. On debugging, I noticed that the loadbalancer was still in creating and was throwing an incorrectState error for the backendAddition step. The work-request for the loadbalancer also clearly failed at a later stage in our logs. Because of this, when we issue a delete command on the failed cluster it never suceeds.

**What you expected to happen**:
Clusters should get deleted successfully without any impact due to dependent resources.
1. capioci should not create a machine without checking the loadbalancer status as active. 
2. If the loadbalancer creation fails and is deleted, it should check the work-request(which will be available in failed state if the loadbalancer is not available as failed state) and subsequently proceed with the other deletions and delete the cluster successfully.

**How to reproduce it (as minimally and precisely as possible)**:
On OCI, we are not sure on the ways to reproduce it but I can briefly explain the steps on our environment. 
Apply the cluster CRD yaml to create a cluster. Once LB creation starts, please check if the checks are happening multiple times before machine creation is triggered. This can be done by reduce your checking timeframe in the code to make sure the creating state is checked multiple times. It could be timed out if the loadbalancer is stuck in creating before you go ahead with the machine reconciliation.

**Anything else we need to know?**:

**Environment:**

- CAPOCI version: v0.11.0
- Cluster-API version (use `clusterctl version`): 1.4.0
- Kubernetes version (use `kubectl version`):1.25.7
- Docker version (use `docker info`):N/A
- OS (e.g. from `/etc/os-release`): Oracle Linux 8

### PR DESCRIPTION
**Pull request by shyamradhakrishnan**
**What this PR does / why we need it**:
* Retry on create/delete backend failure
* Check for LB/NLB status before reconciliation. This is to make sure that CAPOCI do not proceed with machine creation if the LB creation fails.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #331 , #332

### CODE REVIEW

**Comment by shyamradhakrishnan** [comment]
unit test
```
?   	github.com/oracle/cluster-api-provider-oci	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/api/v1beta1	54.676s	coverage: 23.7% of statements
ok  	github.com/oracle/cluster-api-provider-oci/api/v1beta2	0.038s	coverage: 15.6% of statements
?   	github.com/oracle/cluster-api-provider-oci/cloud/config	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/metrics	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/cloud/ociutil	0.011s	coverage: 19.6% of statements
ok  	github.com/oracle/cluster-api-provider-oci/cloud/scope	239.745s	coverage: 75.1% of statements
?   	github.com/oracle/cluster-api-provider-oci/cloud/scope/mocks	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/base	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/base/mock_base	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute/mock_compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/computemanagement	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/computemanagement/mock_computemanagement	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/containerengine	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/containerengine/mock_containerengine	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity/mock_identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/loadbalancer	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/loadbalancer/mock_lb	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer/mock_nlb	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn/mock_vcn	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/cloud/util	0.264s	coverage: 73.4% of statements
ok  	github.com/oracle/cluster-api-provider-oci/controllers	26.885s	coverage: 57.9% of statements
ok  	github.com/oracle/cluster-api-provider-oci/exp/api/v1beta1	13.791s	coverage: 15.2% of statements
ok  	github.com/oracle/cluster-api-provider-oci/exp/api/v1beta2	0.016s	coverage: 4.8% of statements
ok  	github.com/oracle/cluster-api-provider-oci/exp/controllers	0.983s	coverage: 56.0% of statements
?   	github.com/oracle/cluster-api-provider-oci/feature	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/version	[no test files]
go tool cover -func=coverage.out -o coverage.txt
go tool cover -html=coverage.out -o coverage.html
```

**Comment by shyamradhakrishnan** [comment]
e2e
```
  STEP: Tearing down the management cluster @ 09/14/23 10:43:58.283
  << Timeline
------------------------------

Ran 7 of 28 Specs in 3321.112 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 21 Skipped
```

File: cloud/scope/load_balancer_reconciler.go [hunk 1]
```diff
@@ -37,6 +37,9 @@ func (s *ClusterScope) ReconcileApiServerLB(ctx context.Context) error {
 		return err
 	}
 	if lb != nil {
+		if lb.LifecycleState != loadbalancer.LoadBalancerLifecycleStateActive {
+			return errors.New("load balancer is not in active state, hence reconciliation cannot happen")
```
Comment (joekr) [inline cloud/scope/load_balancer_reconciler.go:41]: What about something like 

```suggestion
			return errors.New(fmt.Sprintf("load balancer is not in %s. Waiting for active state.", lb.LifecycleState))
```

or something. 🤷 This way we tell the user we aren't moving forward, but also let them know the current state.

Also what happens if the LB is in a failed state? Will we sit here forever waiting?

File: cloud/scope/machine.go [hunk 2]
```diff
@@ -521,33 +521,29 @@ func (m *MachineScope) ReconcileCreateInstanceOnLB(ctx context.Context) error {
...
+			// work request, the create backend call may throw an error which is ok, as reconcile will go into
+			// an exponential backoff
+			resp, err := m.LoadBalancerClient.CreateBackend(ctx, loadbalancer.CreateBackendRequest{
+				LoadBalancerId: loadbalancerId,
+				BackendSetName: backendSet.Name,
+				CreateBackendDetails: loadbalancer.CreateBackendDetails{
+					IpAddress: common.String(instanceIp),
+					Port:      common.Int(int(m.OCIClusterAccessor.GetControlPlaneEndpoint().Port)),
+				},
+				OpcRetryToken: ociutil.GetOPCRetryToken("%s-%s", "create-backend", string(m.OCIMachine.UID)),
```
Comment (joekr) [inline cloud/scope/machine.go:536]: This is what makes it idempotent correct?

File: cloud/scope/network_load_balancer_reconciler.go [hunk 3]
```diff
@@ -37,6 +36,9 @@ func (s *ClusterScope) ReconcileApiServerNLB(ctx context.Context) error {
 		return err
 	}
 	if nlb != nil {
+		if nlb.LifecycleState != networkloadbalancer.LifecycleStateActive {
+			return errors.New("network load balancer is not in active state, hence reconciliation cannot happen")
```
Comment (joekr) [inline cloud/scope/network_load_balancer_reconciler.go:40]: Thoughts about doing something like described in `load_balancer_reconciler.go`?

File: cloud/scope/machine.go (hunk 2 above)
Comment (shyamradhakrishnan) [reply cloud/scope/machine.go:536]: yes

File: cloud/scope/load_balancer_reconciler.go (hunk 1 above)
Comment (shyamradhakrishnan) [reply cloud/scope/load_balancer_reconciler.go]: fixed, please check..

File: cloud/scope/network_load_balancer_reconciler.go (hunk 3 above)
Comment (shyamradhakrishnan) [reply cloud/scope/network_load_balancer_reconciler.go]: fixed, please check..

File: cloud/scope/load_balancer_reconciler.go (hunk 1 above)
Comment (shyamradhakrishnan) [reply cloud/scope/load_balancer_reconciler.go]: yes, in case of failed state, or in any non active state, we will go into exponential backoff will the operator goes off and investigates. We would have tried recreating the LB but that would have been more code changes and I did not want take that risk at this point.

**Review by joekr — APPROVED** [review]
